export type SitePage = { eyebrow: string; title: string; emphasis: string; description: string; heading: string; body: string; bullets?: string[]; links?: { label: string; href: string }[] };

// Frontend defaults live here so the API response can replace them without changing page UI.
export const mockChurch = { name: "Ingata Church", city: "Kigali", country: "Rwanda", serviceSchedule: "To be confirmed", address: "To be confirmed" };
export const mockServices = ["Sunday worship", "Bible study", "Prayer meetings", "Youth services", "Children’s services", "Special services"];
export const mockChurchValues = ["Faith", "Love", "Worship", "Service", "Community", "Spiritual growth"];
export const mockMinistries = [
  { name: "Children’s Ministry", slug: "children", description: "A welcoming place for children to learn about faith, build friendships and grow." },
  { name: "Youth Ministry", slug: "youth", description: "Faith, friendship and meaningful activities for young people." },
  { name: "Women’s Ministry", slug: "women", description: "Connection, encouragement and spiritual growth for women." },
  { name: "Men’s Ministry", slug: "men", description: "Community, discipleship and opportunities to serve together." },
  { name: "Worship Ministry", slug: "worship", description: "Use music and creative gifts to help lead the church in worship." },
  { name: "Prayer Ministry", slug: "prayer", description: "Join others in prayer for the church, our neighbors and the wider world." },
  { name: "Outreach Ministry", slug: "outreach", description: "Share care and practical support beyond the church community." },
];
export const mockLeaders: { name: string; role: string; imageUrl?: string }[] = [];
export const mockEvents: { title: string; date: string; location: string }[] = [];
export const mockSermons: { title: string; speaker: string; date: string }[] = [];
export const mockAnnouncements: { title: string; description: string; publishedAt?: string }[] = [];
export const mockResources: { title: string; description: string; href?: string }[] = [];
export const mockSocialLinks: { label: string; href: string }[] = [];

export const sitePages: Record<string, SitePage> = {
  "/about/our-story": { eyebrow: "OUR STORY", title: "A story still", emphasis: "being written.", description: "Get to know Ingata Church and the community growing together in Kigali.", heading: "Rooted here. Growing together.", body: "Ingata is a church community in Kigali, Rwanda. We gather to worship, grow in faith, build relationships and serve our neighbors. The church’s history and milestones will be shared here as approved details are prepared.", links: [{ label: "Mission and vision", href: "/about/mission-vision" }, { label: "What we believe", href: "/about/beliefs" }] },
  "/about/mission-vision": { eyebrow: "OUR PURPOSE", title: "A life shaped by", emphasis: "faith and hope.", description: "The purpose and direction that guide Ingata Church as we worship, grow and serve.", heading: "Mission and vision", body: "Our mission and vision statements are being prepared with church leadership. We are committed to sharing approved guidance that reflects the heart and work of the Ingata community.", bullets: ["Worship with an open heart", "Grow in faith together", "Serve our neighbors with care"] },
  "/about/beliefs": { eyebrow: "WHAT WE BELIEVE", title: "Faith at the", emphasis: "center.", description: "Explore the beliefs and values that shape life at Ingata Church.", heading: "A shared foundation", body: "Ingata Church is a Christian community seeking to follow Jesus, grow through Scripture and serve with compassion. The full statement of faith will be published after church approval.", bullets: ["Faith in Jesus Christ", "The importance of Scripture and prayer", "Love, welcome and service"] },
  "/about/leadership": { eyebrow: "OUR LEADERSHIP", title: "People who", emphasis: "serve.", description: "Meet the people who support worship, ministry and care across the Ingata community.", heading: "Serving the church together", body: "Leadership profiles, ministry roles and approved biographies will be added as they become available. For now, contact the church if you would like to connect with a ministry leader.", links: [{ label: "Contact the church", href: "/contact" }] },
  "/ministries/children": { eyebrow: "MINISTRIES · CHILDREN", title: "A place for little", emphasis: "ones to grow.", description: "A warm, age-appropriate place for children to learn about faith, build friendships and feel part of church life.", heading: "Growing in faith together", body: "Our children’s ministry welcomes families and helps young people explore faith in a caring community. Ask us about age groups, schedules and family support.", links: [{ label: "Ask about children’s ministry", href: "/contact?topic=children" }] },
  "/ministries/youth": { eyebrow: "MINISTRIES · YOUTH", title: "Faith for the", emphasis: "next generation.", description: "Faith, friendship and meaningful activities for young people in Kigali.", heading: "A community to grow with", body: "Youth ministry creates room to ask honest questions, build friendships and develop a life of faith. Reach out for current meeting details.", links: [{ label: "Ask about youth ministry", href: "/contact?topic=youth" }] },
  "/ministries/women": { eyebrow: "MINISTRIES · WOMEN", title: "Connection and", emphasis: "encouragement.", description: "Find community, encouragement and opportunities for spiritual growth.", heading: "Growing side by side", body: "Women’s ministry brings people together for fellowship, prayer and shared learning. Contact us for upcoming gatherings and ways to connect.", links: [{ label: "Ask about women’s ministry", href: "/contact?topic=women" }] },
  "/ministries/men": { eyebrow: "MINISTRIES · MEN", title: "Growing through", emphasis: "community.", description: "Build meaningful connections, grow in discipleship and find ways to serve.", heading: "Faith in everyday life", body: "Men’s ministry offers opportunities for fellowship, prayer, learning and service. Ask the church for current meeting information.", links: [{ label: "Ask about men’s ministry", href: "/contact?topic=men" }] },
  "/ministries/worship": { eyebrow: "MINISTRIES · WORSHIP", title: "Make room for", emphasis: "worship.", description: "Use music and creative gifts to help lead the church in worship.", heading: "Worship is shared", body: "The worship ministry serves the congregation through music and creative expression. If you are interested in serving, tell us about your gifts and experience.", links: [{ label: "Connect with worship ministry", href: "/contact?topic=worship" }] },
  "/ministries/prayer": { eyebrow: "MINISTRIES · PRAYER", title: "There is room to", emphasis: "pray together.", description: "Join others in prayer for the church, our neighbors and the wider world.", heading: "A community held in prayer", body: "Prayer is part of how we care for one another. You can share a request with the church prayer team or ask about joining a prayer gathering.", links: [{ label: "Share a prayer request", href: "/prayer-request" }] },
  "/ministries/outreach": { eyebrow: "MINISTRIES · OUTREACH", title: "Care beyond our", emphasis: "own doors.", description: "Discover practical ways to serve neighbors and support the wider Kigali community.", heading: "Faith expressed through care", body: "Outreach ministry connects people who want to offer practical support and compassion beyond the church community. Contact us to learn about current opportunities.", links: [{ label: "Ask about outreach", href: "/contact?topic=outreach" }] },
  "/resources": { eyebrow: "RESOURCES", title: "Tools for your", emphasis: "faith journey.", description: "Find helpful church resources, teaching and practical information for life and faith.", heading: "Resources for the week ahead", body: "Study guides, church documents and other approved resources will be listed here as they become available. You can also explore recent messages and upcoming services.", links: [{ label: "Browse sermons", href: "/sermons" }, { label: "Service information", href: "/services" }] },
  "/faqs": { eyebrow: "FREQUENTLY ASKED QUESTIONS", title: "A few helpful", emphasis: "answers.", description: "What to expect when you visit, where we meet and how to get involved.", heading: "Planning a visit", body: "Service times and the exact meeting location are being confirmed. Contact us before you travel and we will share the latest details.", bullets: ["What should I wear? Come as you are.", "Can I bring children? Families are welcome.", "How can I get involved? Explore ministries or contact the church.", "How can I request prayer? Use our private prayer request form."] },
  "/privacy-policy": { eyebrow: "LEGAL", title: "Privacy", emphasis: "policy.", description: "How Ingata Church handles information shared through this website.", heading: "Your privacy matters", body: "This frontend is a demonstration. The church’s approved privacy policy, including data handling, retention and contact details, should be added before production use." },
  "/terms-and-conditions": { eyebrow: "LEGAL", title: "Terms and", emphasis: "conditions.", description: "Terms for using the Ingata Church website.", heading: "Website terms", body: "The approved terms of use will be published here before the website is launched. Please contact the church with questions about information on this site." },
  "/cookie-policy": { eyebrow: "LEGAL", title: "Cookie", emphasis: "policy.", description: "Information about cookies and similar technologies used on this website.", heading: "Cookies and this website", body: "The approved cookie policy and any consent controls should be added when production analytics or cookie-based services are configured." },
};

export const adminSections = [
  ["Overview", "/admin"], ["Sermons", "/admin/sermons"], ["Events", "/admin/events"],
  ["Ministries", "/admin/ministries"], ["Announcements", "/admin/announcements"],
  ["Resources", "/admin/resources"], ["Leadership", "/admin/leadership"],
  ["Media library", "/admin/media"], ["Inquiries", "/admin/inquiries"],
  ["Prayer requests", "/admin/prayer-requests"], ["Settings", "/admin/settings"],
] as const;

export const adminContent: Record<string, { title: string; description: string; columns: string[]; records: string[][] }> = {
  sermons: { title: "Sermons", description: "Manage published messages and media details.", columns: ["TITLE", "SPEAKER", "DATE", "STATUS"], records: [["Room to grow", "Pastoral team", "Draft", "Draft"], ["Faith in community", "Pastoral team", "Draft", "Draft"]] },
  events: { title: "Events", description: "Keep the church calendar and event details up to date.", columns: ["EVENT", "DATE", "LOCATION", "STATUS"], records: [["Sunday gathering", "To be confirmed", "Kigali", "Draft"]] },
  ministries: { title: "Ministries", description: "Manage ministry descriptions, contacts and schedules.", columns: ["MINISTRY", "LEADER", "SCHEDULE", "STATUS"], records: [["Children’s ministry", "Not assigned", "To be confirmed", "Draft"], ["Youth ministry", "Not assigned", "To be confirmed", "Draft"]] },
  announcements: { title: "Announcements", description: "Publish community news and church updates.", columns: ["TITLE", "CATEGORY", "UPDATED", "STATUS"], records: [["Welcome to Ingata", "Community", "—", "Draft"]] },
  resources: { title: "Resources", description: "Organize documents, guides and helpful links.", columns: ["RESOURCE", "TYPE", "UPDATED", "STATUS"], records: [["Church welcome guide", "Document", "—", "Draft"]] },
  leadership: { title: "Leadership", description: "Maintain approved leader biographies and ministry roles.", columns: ["NAME", "ROLE", "MINISTRY", "STATUS"], records: [["Profile to be added", "Leadership role", "Church", "Draft"]] },
  media: { title: "Media library", description: "Prepare images and media for church content.", columns: ["FILE", "TYPE", "ADDED", "STATUS"], records: [["No media uploaded", "—", "—", "Empty"]] },
  inquiries: { title: "Inquiries", description: "Review contact and visitor messages when connected to the API.", columns: ["SENDER", "SUBJECT", "RECEIVED", "STATUS"], records: [["No inquiries yet", "—", "—", "Empty"]] },
  "prayer-requests": { title: "Prayer requests", description: "Review requests shared with the church prayer team.", columns: ["REQUEST", "RECEIVED", "FOLLOW-UP", "STATUS"], records: [["No requests yet", "—", "—", "Empty"]] },
  settings: { title: "Settings", description: "Church profile and website preferences.", columns: ["SETTING", "VALUE", "DESCRIPTION"], records: [["Church name", "Ingata Church", "Public name shown across the website"], ["Location", "Kigali, Rwanda", "Add approved street address"], ["Service schedule", "To be confirmed", "Add approved times and venue"]] },
};
