import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { getPublicData, type ChurchEvent, type Sermon } from "../lib/church-api";
import { mockMinistries } from "../lib/site-content";

export const metadata: Metadata = { title: "A Place to Belong", description: "A community of faith, hope and open doors in Kigali. Join us for worship, find your people, and grow in faith together.", alternates: { canonical: "/" } };

export default async function Home() {
  const [events, sermons] = await Promise.all([
    getPublicData<ChurchEvent[]>("/events"),
    getPublicData<Sermon[]>("/sermons"),
  ]);
  return <main>
    <section className="relative flex min-h-[36rem] items-center overflow-hidden bg-primary text-primary-foreground md:min-h-[42rem]">
      <Image alt="Friends gathered together in community" className="object-cover object-[center_42%]" fill priority sizes="100vw" src="https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=2200&q=88" unoptimized />
      <div aria-hidden="true" className="home-hero-overlay absolute inset-0" />
      <div className="home-hero-content page-container relative py-24">
        <p className="eyebrow flex items-center gap-2 text-primary-foreground"><span className="h-1.5 w-1.5 rounded-full bg-accent" /> A PLACE TO BELONG</p>
        <h1 className="mt-7 max-w-3xl text-[clamp(3.25rem,8vw,7.25rem)] font-medium leading-[.98] tracking-[-.065em]">Faith grows<br />better <em className="font-display text-accent">together.</em></h1>
        <p className="mt-6 max-w-md text-base leading-7 text-primary-foreground/85">We are a community learning the way of Jesus, loving our neighbors and making room for everyone.</p>
        <div className="mt-8 flex flex-wrap items-center gap-3"><Link className="button button-secondary" href="/plan-your-visit">Plan your visit <span aria-hidden="true">↗</span></Link><Link className="button button-outline" href="/sermons">Watch sermons <span aria-hidden="true">↗</span></Link></div>
      </div>
      <p className="absolute bottom-6 right-6 hidden font-display text-sm italic text-primary-foreground sm:block md:right-12">Rooted in faith. Open to all.</p>
    </section>

    <section className="page-container section-space" id="about"><p className="eyebrow text-muted">A LITTLE ABOUT US</p><div className="mt-8 grid gap-8 md:grid-cols-2 md:items-end"><h2 className="text-4xl font-medium leading-[1.05] tracking-[-.05em] sm:text-6xl">Church should feel<br />like a <em className="font-display text-clay">deep breath.</em></h2><div className="max-w-md"><p className="text-base leading-7 text-muted">Come as you are. Bring your questions, your whole family, or just yourself. There is a seat at the table and a story still being written—with you in it.</p><Link className="mt-5 inline-flex border-b border-text/20 pb-2 text-sm font-bold" href="/about/our-story">Discover our story <span className="ml-2 text-clay" aria-hidden="true">↗</span></Link></div></div><div className="mt-12 flex flex-wrap items-center justify-between gap-4 border-y border-border px-2 py-6 text-[10px] font-bold tracking-[.2em] text-muted"><span>WORSHIP</span><span className="text-clay" aria-hidden="true">✳</span><span>GROW</span><span className="text-clay" aria-hidden="true">✳</span><span>SERVE</span><span className="text-clay" aria-hidden="true">✳</span><span>BELONG</span></div></section>

    <section className="grid bg-primary text-primary-foreground md:grid-cols-2" id="services"><div className="relative min-h-72 overflow-hidden md:min-h-[34rem]"><Image alt="People enjoying time together" className="object-cover" fill sizes="(max-width: 768px) 100vw, 50vw" src="https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1300&q=85" unoptimized /></div><div className="flex flex-col items-start justify-center px-6 py-14 sm:px-12 lg:px-20"><p className="eyebrow">MAKE ROOM FOR SUNDAY</p><h2 className="mt-6 text-5xl font-medium leading-none tracking-[-.05em] sm:text-6xl">There’s a<br />place for <em className="font-display text-accent">you.</em></h2><p className="mt-5 max-w-md text-base leading-7 text-primary-foreground/75">We would love to worship with you. Come a little early, meet the community and find a place to belong.</p><div className="my-7 w-full max-w-md border-y border-primary-foreground/25 py-4"><strong className="block text-sm">Sunday worship</strong><span className="mt-1 block text-sm text-primary-foreground/70">Service time and location to be confirmed</span></div><Link className="button button-secondary" href="/services">View service information <span aria-hidden="true">↗</span></Link></div></section>

    <section className="page-container section-space" id="ministries"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow text-muted">FIND YOUR PEOPLE</p><h2 className="mt-5 text-4xl font-medium leading-tight tracking-[-.05em] sm:text-6xl">There’s more than<br /><em className="font-display text-clay">one way in.</em></h2></div><p className="max-w-sm text-base leading-7 text-muted">Faith takes shape in community. Explore ways to connect, contribute and grow.</p></div><div className="mt-10 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{mockMinistries.map((ministry, index) => <Link className="group flex min-h-28 items-center justify-between bg-surface px-5 py-4 transition hover:bg-surface-strong" href={`/ministries/${ministry.slug}`} key={ministry.slug}><span><small className="eyebrow text-muted">{String(index + 1).padStart(2, "0")} / MINISTRY</small><strong className="mt-3 block font-medium">{ministry.name}</strong></span><span className="text-lg text-clay transition group-hover:translate-x-1" aria-hidden="true">↗</span></Link>)}</div><Link className="mt-6 inline-flex text-sm font-bold" href="/ministries">Explore all ministries <span className="ml-2 text-clay" aria-hidden="true">↗</span></Link></section>

    <section className="bg-primary px-5 py-16 text-primary-foreground lg:py-24" id="events"><div className="page-container"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">LIFE AT INGATA</p><h2 className="mt-5 text-4xl font-medium leading-tight tracking-[-.05em] sm:text-6xl">Good things<br />are <em className="font-display text-accent">coming up.</em></h2></div><Link className="button button-outline" href="/events">All events <span aria-hidden="true">↗</span></Link></div><div className="mt-10 border-t border-primary-foreground/25">{events?.length ? events.slice(0, 3).map((event) => <Link className="grid grid-cols-[1fr_24px] items-center border-b border-primary-foreground/25 py-5 transition hover:px-2" href={`/events/${event.id}`} key={event.id}><span><strong className="block text-sm">{event.name}</strong><small className="mt-1 block text-sm text-primary-foreground/65">{event.date} · {event.time} · {event.location}</small></span><span className="text-accent" aria-hidden="true">↗</span></Link>) : <p className="border-b border-primary-foreground/25 py-6 text-sm text-primary-foreground/75">Confirmed events will appear here when published. <Link className="font-bold text-accent underline" href="/contact?topic=events">Ask what’s coming up.</Link></p>}</div></div></section>

    <section className="page-container section-space" id="sermons"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-muted">WORDS FOR THE WEEK</p><h2 className="mt-5 text-4xl font-medium leading-tight tracking-[-.05em] sm:text-5xl">Room to pause.<br />Space to <em className="font-display text-primary">listen.</em></h2></div><Link className="button button-outline" href="/sermons">Browse sermons <span aria-hidden="true">↗</span></Link></div>{sermons?.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{sermons.slice(0, 3).map((sermon) => <article className="surface-card p-4 sm:p-6" key={sermon.id}><p className="eyebrow text-primary">{sermon.category} · {sermon.date}</p><h3 className="mt-3 text-xl font-semibold"><Link className="hover:text-primary-hover" href={`/sermons/${sermon.id}`}>{sermon.title}</Link></h3><p className="mt-2 text-sm text-muted">{sermon.speaker}{sermon.scripture ? ` · ${sermon.scripture}` : ""}</p>{sermon.audioUrl && <audio className="mt-4 w-full" controls preload="none" src={sermon.audioUrl}>Audio playback is not supported by your browser.</audio>}</article>)}</div> : <p className="mt-7 max-w-lg border-y border-border py-6 text-sm leading-6 text-muted">Published messages will appear here with speaker, date and Scripture details. Until then, browse the sermon library when you are ready.</p>}</section>

    <section className="bg-surface-strong px-5 py-14"><div className="page-container"><p className="eyebrow text-muted">STAY IN THE LOOP</p><h2 className="mt-4 text-3xl font-medium tracking-[-.04em]">News, notes & <em className="font-display text-clay">good things.</em></h2><p className="mt-3 max-w-lg text-base leading-7 text-muted">Church announcements, community news and ministry updates—all in one place.</p><Link className="mt-4 inline-flex text-sm font-bold" href="/announcements">Read announcements <span className="ml-2 text-clay" aria-hidden="true">↗</span></Link></div></section>

    <section className="bg-primary px-5 py-16 text-primary-foreground lg:py-24" id="visit"><div className="page-container grid gap-10 md:grid-cols-[1.2fr_.8fr] md:items-center"><div><p className="eyebrow">YOUR NEXT CHAPTER COULD START HERE</p><h2 className="mt-6 text-4xl font-medium leading-tight tracking-[-.05em] sm:text-6xl">Come as you are.<br /><em className="font-display text-accent">Leave with more.</em></h2><p className="mt-5 max-w-md text-base leading-7 text-primary-foreground/75">We will save you a seat, show you around and help you feel at home.</p><Link className="button button-secondary mt-7" href="/plan-your-visit">Plan a visit <span aria-hidden="true">↗</span></Link><Link className="ml-4 inline-flex min-h-12 items-center text-sm font-semibold text-primary-foreground underline underline-offset-4" href="/prayer-request">Share a prayer request</Link></div><div className="overflow-hidden border border-primary-foreground/20"><iframe title="Map of Kigali, Rwanda" className="h-64 w-full border-0 grayscale" loading="lazy" src="https://maps.google.com/maps?q=Kigali%2C%20Rwanda&output=embed" /><p className="px-4 py-3 text-sm text-primary-foreground/75">Kigali, Rwanda · Exact church address to be added</p></div></div></section>
  </main>;
}
