import { PageHero } from "../../components/page-hero";
import { SubmissionForm } from "../../components/submission-form";

export default async function ContactPage({ searchParams }: { searchParams: Promise<{ topic?: string }> }) {
  const { topic } = await searchParams;
  const initialMessage = topic ? `I’d like to learn more about ${topic.slice(0, 120)}.` : "";
  return <main><PageHero eyebrow="VISIT · CONNECT · PRAY" title="We’d love to" emphasis="hear from you." description="Planning your first visit, asking about a ministry or carrying something you’d like prayer for? Reach out and our team will follow up." />
    <section className="mx-auto grid max-w-7xl gap-12 px-6 py-14 lg:grid-cols-[.75fr_1.25fr] lg:px-10 lg:py-20"><aside><p className="text-[10px] font-bold tracking-[.2em] text-muted">GET IN TOUCH</p><h2 className="mt-4 text-4xl font-medium">The door is<br /><em className="font-display text-clay">open.</em></h2><p className="mt-4 text-sm leading-7 text-muted">We’re in Kigali, Rwanda. Our approved street address, phone number, email and WhatsApp details will be added here.</p><div className="mt-7 border-y border-ink/15 py-5"><p className="text-xs font-bold">CONTACT CHANNELS</p><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-muted">PHONE</dt><dd className="mt-1">Church number to be added</dd></div><div><dt className="text-xs text-muted">EMAIL</dt><dd className="mt-1">Church email to be added</dd></div><div><dt className="text-xs text-muted">WHATSAPP</dt><dd className="mt-1">Link to be added if enabled</dd></div></dl></div><div className="mt-6 border-b border-ink/15 pb-5"><p className="text-xs font-bold">VISIT US</p><p className="mt-2 text-sm text-muted">Kigali, Rwanda</p><p className="mt-1 text-xs text-muted">Exact service location to be confirmed</p><a className="mt-3 inline-block text-sm font-bold" href="https://maps.google.com/?q=Kigali%2C%20Rwanda" target="_blank" rel="noreferrer">Directions to Kigali ↗</a></div><div className="mt-5 min-h-56 overflow-hidden border border-ink/10"><iframe title="Map of Kigali, Rwanda" className="h-56 w-full border-0 grayscale" loading="lazy" src="https://maps.google.com/maps?q=Kigali%2C%20Rwanda&output=embed" /></div></aside>
      <div className="space-y-12"><div className="surface-card p-6 sm:p-9"><p className="text-[10px] font-bold tracking-[.2em] text-clay">GENERAL CONTACT · MINISTRY QUESTIONS</p><h2 className="mt-3 text-2xl font-semibold">Send us a message</h2><p className="mb-6 mt-2 text-sm text-muted">For general questions, visitor inquiries or ministry information.</p><SubmissionForm initialMessage={initialMessage} type="contact" /></div><div className="grid gap-6 sm:grid-cols-2"><div className="border border-ink/15 p-6"><p className="text-[10px] font-bold tracking-[.2em] text-clay">PLAN A VISIT</p><h2 className="mt-3 text-xl font-semibold">We’ll save you a seat.</h2><p className="mb-5 mt-2 text-sm leading-6 text-muted">Tell us you’re coming and we can help you know what to expect.</p><SubmissionForm type="visitor" compact /></div><div className="border border-ink/15 p-6"><p className="text-[10px] font-bold tracking-[.2em] text-clay">PRAYER REQUEST</p><h2 className="mt-3 text-xl font-semibold">You don’t have to carry it alone.</h2><p className="mb-5 mt-2 text-sm leading-6 text-muted">Share a request with the church prayer team.</p><SubmissionForm type="prayer" compact /></div></div></div>
    </section>
  </main>;
}
