import Link from "next/link";
import { PageHero } from "@/components/site/page-hero";
import { getPublicData, type PublicContent } from "@/lib/api/church-api";
import { mockServices } from "@/lib/content/church-defaults";

export default async function ServicesPage() {
  const response = await getPublicData<{ items: PublicContent[] }>("/content/services?limit=50");
  const services = response?.items ?? [];
  const detail = (record: PublicContent, key: string) => typeof record.details[key] === "string" ? record.details[key] as string : "To be confirmed";
  return <main><PageHero eyebrow="GATHER WITH US" title="There’s a place" emphasis="for you." description="Find worship gatherings, Bible studies, prayer meetings and special services. The schedule and venue details below will be updated with church-approved information." />
    <section className="page-container section-space"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow text-muted">REGULAR GATHERINGS</p><h2 className="mt-4 text-4xl font-medium">Service <em className="font-display text-clay">schedule.</em></h2>{services.length ? <div className="mt-7 divide-y divide-border border-y border-border">{services.map((service) => <article className="py-6" key={service.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-semibold">{service.title}</h3>{service.description && <p className="mt-2 text-sm text-muted">{service.description}</p>}</div><span className="bg-surface-strong px-3 py-2 text-xs font-semibold">{detail(service, "type")}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-xs text-muted">DAY & TIME</dt><dd className="mt-1">{detail(service, "day")} · {detail(service, "time")}</dd></div><div><dt className="text-xs text-muted">LOCATION</dt><dd className="mt-1">{detail(service, "location")}</dd></div><div><dt className="text-xs text-muted">SPECIAL INFORMATION</dt><dd className="mt-1">{detail(service, "specialInformation")}</dd></div></dl></article>)}</div> : <article className="mt-7 border-y border-border py-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-semibold">Service schedule being confirmed</h3><p className="mt-2 text-sm text-muted">Approved service times, types and locations will be listed here.</p></div></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-xs text-muted">DAY & TIME</dt><dd className="mt-1">To be confirmed</dd></div><div><dt className="text-xs text-muted">LOCATION</dt><dd className="mt-1">To be confirmed</dd></div><div><dt className="text-xs text-muted">SERVICE TYPE</dt><dd className="mt-1">To be confirmed</dd></div></dl></article>}<p className="mt-5 text-sm leading-6 text-muted">For the latest schedule or special service information, please contact the church.</p><Link className="button button-primary mt-5" href="/contact?topic=services">Ask about a service ↗</Link></div><div className="surface-card p-6 sm:p-8"><p className="eyebrow text-muted">SERVICE TYPES</p><ul className="mt-5 divide-y divide-border">{mockServices.map((type, i) => <li className="flex items-center justify-between py-3 text-sm" key={type}><span>{type}</span><span className="font-display text-clay">0{i + 1}</span></li>)}</ul></div></div></section>
  </main>;
}
