import { PageHero } from "../../components/page-hero";

const values = ["Faith", "Love", "Worship", "Service", "Community", "Spiritual growth"];

export default function AboutPage() {
  return <main><PageHero eyebrow="WHO WE ARE" title="A community of faith," emphasis="open to all." description="Learn about Ingata Church—our story, what we believe, the values that guide us and the people who serve our community." />
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10 lg:py-24"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold tracking-[.2em] text-muted">01 / OUR STORY</p><h2 className="mt-5 text-4xl font-medium tracking-tight">A story still<br />being <em className="font-display text-clay">written.</em></h2></div><div className="space-y-4 text-sm leading-7 text-muted"><p>Ingata is a church community in Kigali, Rwanda. We gather to worship, grow in faith, build relationships and serve our neighbors.</p><p>Our history, founding story and milestones will be shared here as the church’s approved information is prepared.</p></div></div>
    <div className="mt-16 grid gap-4 sm:grid-cols-2"><article className="bg-[#eeeadf] p-7 sm:p-9"><p className="text-[10px] font-bold tracking-[.2em] text-clay">OUR MISSION</p><h3 className="mt-4 font-display text-3xl">To proclaim, nurture and serve.</h3><p className="mt-4 text-sm leading-7 text-muted">Our approved mission statement will be published here.</p></article><article className="bg-[#e8e8d9] p-7 sm:p-9"><p className="text-[10px] font-bold tracking-[.2em] text-clay">OUR VISION</p><h3 className="mt-4 font-display text-3xl">A community transformed by hope.</h3><p className="mt-4 text-sm leading-7 text-muted">Our approved vision statement will be published here.</p></article></div>
    <div className="mt-16 grid gap-10 md:grid-cols-2"><div><p className="text-[10px] font-bold tracking-[.2em] text-muted">02 / WHAT GUIDES US</p><h2 className="mt-4 text-4xl font-medium">Core <em className="font-display text-clay">values.</em></h2><div className="mt-6 flex flex-wrap gap-2">{values.map((value) => <span className="border border-ink/15 px-4 py-2 text-sm" key={value}>{value}</span>)}</div><p className="mt-4 text-xs leading-6 text-muted">Values shown are a starting point and should be confirmed by church leadership.</p></div><div><p className="text-[10px] font-bold tracking-[.2em] text-muted">03 / WHAT WE BELIEVE</p><h2 className="mt-4 text-4xl font-medium">Statement of <em className="font-display text-clay">faith.</em></h2><p className="mt-4 text-sm leading-7 text-muted">The church’s approved statement of faith and beliefs will be published here.</p></div></div>
    <div className="mt-16 border-t border-ink/15 pt-10"><p className="text-[10px] font-bold tracking-[.2em] text-muted">04 / LEADERSHIP</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="text-4xl font-medium">People who <em className="font-display text-clay">serve.</em></h2><p className="max-w-md text-sm leading-7 text-muted">Leadership profiles and ministry roles will be added when approved biographies and photos are available.</p></div></div>
    </section>
  </main>;
}
